<a href="https://colab.research.google.com/github/debanjanchatterjee/tuberculosis-drug-resistance-classification/blob/master/Chi_square_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing the librares

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
import csv

# Importing the Dataset

In [23]:
#dataset = pd.read_csv('X_trainData_1.csv')
#labels=pd.read_csv('Y_trainData_1.csv')
dataset = pd.read_csv('X_trainData_chi_squared_PZA.csv')
datalabels=pd.read_csv('X_trainData_column_modified_RIF.csv')


X_train=dataset.iloc[:,:-1].values
y_train=dataset.iloc[:,-1].values

In [24]:
print(X_train)
print(len(X_train[0]))

[[0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
182


In [25]:
print(y_train)

count1=0
count0=0

for n in y_train:
  if n==1:
    count1=count1+1
  else:
    count0=count0+1

print(count1)
print(count0)

[0 0 0 ... 1 1 1]
2246
695


# Building the ANN

In [26]:
ann = tf.keras.models.Sequential()

#class_weight={1:1, 0:5}

ann.add(tf.keras.layers.Dense(units=128, activation='relu'))

ann.add(tf.keras.layers.Dense(units=64, activation='relu'))

ann.add(tf.keras.layers.Dense(units=32, activation='relu'))

ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

ann.fit(X_train, y_train, batch_size = 16, epochs = 100)

Epoch 1/100
184/184 [==============================] - 0s 3ms/step - loss: 0.3571 - accuracy: 0.8147
Epoch 2/100
184/184 [==============================] - 0s 2ms/step - loss: 0.2350 - accuracy: 0.9058
Epoch 3/100
184/184 [==============================] - 0s 2ms/step - loss: 0.2088 - accuracy: 0.9119
Epoch 4/100
184/184 [==============================] - 0s 2ms/step - loss: 0.1729 - accuracy: 0.9361
Epoch 5/100
184/184 [==============================] - 0s 3ms/step - loss: 0.1565 - accuracy: 0.9422
Epoch 6/100
184/184 [==============================] - 0s 2ms/step - loss: 0.1319 - accuracy: 0.9544
Epoch 7/100
184/184 [==============================] - 0s 2ms/step - loss: 0.1194 - accuracy: 0.9592
Epoch 8/100
184/184 [==============================] - 0s 3ms/step - loss: 0.1005 - accuracy: 0.9677
Epoch 9/100
184/184 [==============================] - 0s 2ms/step - loss: 0.0894 - accuracy: 0.9694
Epoch 10/100
184/184 [==============================] - 0s 3ms/step - loss: 0.0881 - accura

In [ ]:
#from xgboost import XGBClassifier
#classifier = XGBClassifier()
#classifier.fit(X_train, y_train)

#from sklearn.ensemble import RandomForestClassifier
#classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
#classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

#Predicting Validation set results 

In [28]:
test_data = pd.read_csv('X_testData_chi_squared_PZA.csv')


X_test=test_data.iloc[:,:].values


print(type(X_test))
print(len(X_test))
print(len(X_test[0]))
print(X_test)

<class 'numpy.ndarray'>
1000
182
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [29]:
#y_pred = classifier.predict_proba(X_test)
#y_pred = classifier.predict(X_test)
y_pred = ann.predict(X_test)
print(y_pred)

print(type(y_pred))
#y_pred = (y_pred > 0.5)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_validation.reshape(len(y_validation),1)),1))

[[1.00000000e+00]
 [9.21645835e-08]
 [1.71043055e-07]
 [2.48337756e-06]
 [9.99399662e-01]
 [1.71043055e-07]
 [1.00000000e+00]
 [2.45990492e-07]
 [9.99945402e-01]
 [1.00000000e+00]
 [9.99999762e-01]
 [2.03041593e-03]
 [3.52886127e-05]
 [9.92937148e-01]
 [2.18546866e-05]
 [9.99117553e-01]
 [9.99942064e-01]
 [2.86596719e-06]
 [1.00000000e+00]
 [9.99997258e-01]
 [1.00000000e+00]
 [2.48337756e-06]
 [1.00000000e+00]
 [1.00000000e+00]
 [8.93612198e-11]
 [1.00000000e+00]
 [1.80552225e-03]
 [2.09874584e-09]
 [6.66268352e-06]
 [3.93935661e-05]
 [5.15085929e-08]
 [9.99993920e-01]
 [3.92321162e-08]
 [1.00000000e+00]
 [9.99995828e-01]
 [9.27220762e-01]
 [1.00000000e+00]
 [1.00000000e+00]
 [9.99399662e-01]
 [1.00000000e+00]
 [1.31005827e-05]
 [1.95691206e-11]
 [1.11610646e-07]
 [9.99190509e-01]
 [8.85720015e-01]
 [8.02874804e-01]
 [1.00000000e+00]
 [2.48337756e-06]
 [4.45506703e-05]
 [6.14088988e-12]
 [1.00000000e+00]
 [9.99999523e-01]
 [5.76592796e-02]
 [9.99981046e-01]
 [1.00000000e+00]
 [1.200345

In [30]:
print(len(y_pred))


1000


In [31]:
submission_data = pd.read_csv('Y_testData_1_nolabels_PZA.csv')

ids=submission_data.iloc[:,:1].values
result=list()
k=0
#print(ids)
#print(y_pred[0])
for i in ids:
  #result.append([ i[0], y_pred[i[0]-1][0] ])
  result.append([ i[0], y_pred[k][0] ])
  #result.append([ i[0], y_pred[k][1] ])
  k=k+1
  #print(y_pred[i[0]-1][0])
  #print('.')

result.insert(0, ['ID','PZA'])
print(result)

[['ID', 'PZA'], [1, 1.0], [2, 9.216458e-08], [3, 1.7104306e-07], [4, 2.4833776e-06], [5, 0.99939966], [6, 1.7104306e-07], [7, 1.0], [8, 2.459905e-07], [9, 0.9999454], [10, 1.0], [11, 0.99999976], [12, 0.002030416], [13, 3.5288613e-05], [14, 0.99293715], [15, 2.1854687e-05], [16, 0.99911755], [17, 0.99994206], [18, 2.8659672e-06], [19, 1.0], [20, 0.99999726], [21, 1.0], [22, 2.4833776e-06], [23, 1.0], [24, 1.0], [25, 8.936122e-11], [26, 1.0], [27, 0.0018055222], [28, 2.0987458e-09], [29, 6.6626835e-06], [30, 3.9393566e-05], [31, 5.1508593e-08], [32, 0.9999939], [33, 3.9232116e-08], [34, 1.0], [35, 0.9999958], [36, 0.92722076], [37, 1.0], [38, 1.0], [39, 0.99939966], [40, 1.0], [41, 1.3100583e-05], [42, 1.956912e-11], [43, 1.11610646e-07], [44, 0.9991905], [45, 0.88572], [46, 0.8028748], [47, 1.0], [48, 2.4833776e-06], [49, 4.455067e-05], [50, 6.14089e-12], [51, 1.0], [52, 0.9999995], [53, 0.05765928], [54, 0.99998105], [55, 1.0], [56, 0.12003451], [57, 5.1508593e-08], [58, 0.8923077], [

In [32]:
file = open('PZA_result.csv', 'w+', newline ='') 
  
# writing the data into the file 
with file:     
    write = csv.writer(file) 
    write.writerows(result) 

# Making the Confusion Matrix