<a href="https://colab.research.google.com/github/debanjanchatterjee/tuberculosis-drug-resistance-classification/blob/master/mtb-isolate-drug-resistance-xgb-nn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing the librares

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
import csv

# Importing the Dataset

In [ ]:
#dataset = pd.read_csv('X_trainData_1.csv')
#labels=pd.read_csv('Y_trainData_1.csv')
dataset = pd.read_csv('X_trainData_column_modified_STR.csv')


X_train=dataset.iloc[:,:-1].values
y_train=dataset.iloc[:,-1].values

In [ ]:
print(X_train)


[[0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
print(y_train)

count1=0
count0=0

for n in y_train:
  if n==1:
    count1=count1+1
  else:
    count0=count0+1

print(count1)
print(count0)

[0 1 0 ... 1 0 1]
1061
1020


# Building the ANN

In [ ]:
#ann = tf.keras.models.Sequential()

#class_weight={1:1, 0:5}

#ann.add(tf.keras.layers.Dense(units=128, activation='relu'))

#ann.add(tf.keras.layers.Dense(units=64, activation='relu'))

#ann.add(tf.keras.layers.Dense(units=32, activation='relu'))

#ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

#ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

#ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

#ann.fit(X_train, y_train, batch_size = 16, epochs = 100)

Epoch 1/100
131/131 [==============================] - 0s 3ms/step - loss: 0.5914 - accuracy: 0.7280
Epoch 2/100
131/131 [==============================] - 0s 2ms/step - loss: 0.5040 - accuracy: 0.8592
Epoch 3/100
131/131 [==============================] - 0s 3ms/step - loss: 0.4604 - accuracy: 0.8760
Epoch 4/100
131/131 [==============================] - 0s 3ms/step - loss: 0.4164 - accuracy: 0.8909
Epoch 5/100
131/131 [==============================] - 0s 3ms/step - loss: 0.3947 - accuracy: 0.8976
Epoch 6/100
131/131 [==============================] - 0s 3ms/step - loss: 0.3492 - accuracy: 0.9159
Epoch 7/100
131/131 [==============================] - 0s 3ms/step - loss: 0.3171 - accuracy: 0.9274
Epoch 8/100
131/131 [==============================] - 0s 2ms/step - loss: 0.2890 - accuracy: 0.9356
Epoch 9/100
131/131 [==============================] - 0s 3ms/step - loss: 0.2366 - accuracy: 0.9510
Epoch 10/100
131/131 [==============================] - 0s 3ms/step - loss: 0.1620 - accura

In [ ]:
#from xgboost import XGBClassifier
#classifier = XGBClassifier()
#classifier.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

#Predicting Validation set results 

In [ ]:
test_data = pd.read_csv('X_testData_1_modified.csv')


X_test=test_data.iloc[:,:].values


print(type(X_test))
print(len(X_test))
print(len(X_test[0]))
print(X_test)

<class 'numpy.ndarray'>
1000
219
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
#y_pred = classifier.predict_proba(X_test)
y_pred = classifier.predict(X_test)
print(y_pred)

print(type(y_pred))
#y_pred = (y_pred > 0.5)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_validation.reshape(len(y_validation),1)),1))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0
 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0
 1 0 1 1 1 1 1 0 0 1 1 0 0 0 0 0 1 0 0 1 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0
 1 0 0 1 1 1 1 0 0 1 0 1 0 1 0 1 0 1 0 1 1 1 0 1 1 1 0 1 1 0 1 0 0 0 1 0 0
 0 1 1 1 0 1 1 1 1 0 1 0 1 1 1 0 0 1 1 0 1 1 0 1 0 1 1 0 0 1 1 1 0 0 0 0 0
 1 1 0 0 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 1 1 1 1 1 1 1 1 

In [ ]:
print(len(y_pred))


1000


In [ ]:
submission_data = pd.read_csv('Y_testData_1_nolabels_STR.csv')

ids=submission_data.iloc[:,:1].values
result=list()

#print(ids)
#print(y_pred[0])
for i in ids:
  result.append([ i[0], y_pred[i[0]-1] ])
  #print(y_pred[i[0]-1][0])

result.insert(0, ['ID','STR'])
print(result)

[['ID', 'STR'], [198, 0], [199, 1], [200, 0], [201, 1], [202, 0], [203, 1], [204, 0], [205, 1], [206, 1], [207, 1], [208, 0], [209, 1], [210, 1], [211, 1], [212, 0], [213, 1], [214, 1], [215, 0], [216, 1], [217, 0], [218, 0], [219, 0], [220, 1], [221, 0], [222, 0], [223, 0], [224, 1], [225, 1], [226, 1], [227, 0], [228, 1], [229, 1], [230, 1], [231, 1], [232, 0], [233, 1], [234, 0], [235, 1], [236, 1], [237, 1], [238, 0], [239, 0], [240, 1], [241, 1], [242, 0], [243, 1], [244, 1], [245, 0], [246, 1], [247, 0], [248, 1], [249, 1], [250, 0], [251, 0], [252, 1], [253, 1], [254, 1], [255, 0], [256, 0], [257, 0], [258, 0], [259, 0], [260, 1], [261, 1], [262, 0], [263, 0], [264, 1], [265, 1], [266, 1], [267, 1], [268, 1], [269, 1], [270, 0], [271, 1], [272, 0], [273, 1], [274, 1], [275, 1], [276, 1], [277, 1], [278, 1], [279, 1], [280, 1], [281, 1], [282, 1], [283, 1], [284, 1], [285, 1], [286, 1], [287, 1], [288, 1], [289, 1], [290, 1], [291, 1], [292, 1], [293, 1], [294, 1], [296, 1], [297

In [ ]:
file = open('STR_result.csv', 'w+', newline ='') 
  
# writing the data into the file 
with file:     
    write = csv.writer(file) 
    write.writerows(result) 

# Making the Confusion Matrix